### ISSUE TITLE
Pressure incorrect (inHg) in weather and sensor entities

### ISSUE THREAD

**Issue by chasut** [briis/smartweather#69]
Just installed, all looks good but noticed that the pressure is reporting low in both the weather and sensors.  The pressure in the mobile app (and website) show 29.87 inHG, but the weather entity and sensor report 29.51.  Probably something in the conversion logic.

BTW, thank you for the integration.  It inspired me to get a Tempest, you should get a commission!

**Comment by briis** [comment]
Hi @chasut 
I will look at it. Of my head I think there is both Sea Level and Station Pressure delivered, so it might be because I use the wrong pressure measurement as compared to the mobile App.

Instead of a commission, I would love just to be able to buy a Tempest unit - they are still not available in Europe 😬

**Comment by briis** [comment]
This was a quick fix. I have just released V2.2.7, which should now display the correct Pressure Value. I am closing this issue.
