### ISSUE TITLE
Pressure Problems

### ISSUE THREAD

**Issue by chasut** [briis/smartweather#72]
Sorry to be a pest, but still seeing odd readings for the pressure.  I have two instances, daily and hourly, they read the same, but the hourly is updated more frequently.  In any case these are the readings for pressure just now:

Pressure Sensor: 29.9
Weather entity: 30.72
WF Application: 30.242 
WF App Station pressure: 29.388
For comparison from the Accuweather site for my location: 30.32

I am just too familiar with inHG to change.  But it is very sensitive to significant digits on conversion.  Although it is not clear if you are converting anything.
Let me know if there is anything I can do to help.  And if you just happen to add another digit to the right of the decimal point on the sensors while you are in there, I wouldn't be upset ;)

Thanks a bunch

**Comment by briis** [comment]
You are not a pest, I like when people get in to the details. It also helps to optimize the functions. And you are right, the conversion routine, was not accurate enough, so instead of converting Millibar to Inches Mercury like this `Mb * 0.03` I now do `Mb * 0.029530` which should be as correct as possible.

The Pressure values are also now presented with 3 decimals when the Imperial Unit System is used. So I hope this displays more correctly.

There might still be minor discrepancies between the APP and this Integration, but that is due to timing on when we retrieve the data.

This will be in the 2.2.8 release coming out later today

**Comment by briis** [comment]
Closed with the 2.2.8 release

**Comment by chasut** [comment]
Absolutely perfect translation to the third digit.  Thank you
