### ISSUE TITLE
Missing Personal Weather Station after installing via HCAS

### ISSUE THREAD

**Issue by johnt-tally** [briis/smartweather#77]
I installed your Weatherflow Smart Weather Integration, with seemingly no issues.  But after the install, when I go to HA/Configuration/Integration, I can find any new integrations named "Personal Weather Station" nor anything named Smart Weather.  I used the file editor to open the config file and I found the HACS custom folder, so it does appear to have installed correctly.  I am on core-2021.7.3 and for HACS, 1.13.2.  Let me know if I can provide any other helpful info.

**Comment by briis** [comment]
Hi,
This happens often and is caused by Webbrowser caching. 
- Make sure you have restarted HA after the install.
- When you are on the Integrations page, do a hard refresh of your browser (CMD+R on a Mac)
- Then click the `+ ADD INTEGRATION` in the lower right corner
- Search for `Weatherflow Smart Weather`and click it to configure

That should be it.

**Comment by johnt-tally** [comment]
Thank you!  Sorry I didn't think of trying that first.  Everything working GREAT.  This was my first HACS integration and I'm super impressed!
